apiVersion: v1
kind: Service
metadata:
  labels:
    kosmos.io/app: coredns
  name: coredns
  namespace: kosmos-system
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: dns
      port: 53
      protocol: UDP
      targetPort: 53
    - name: dns-tcp
      port: 53
      protocol: TCP
      targetPort: 53
    - name: metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    kosmos.io/app: coredns
  sessionAffinity: None
  type: ClusterIP
